### ISSUE TITLE
[TitleAPI] Failed to handle reflection

### ISSUE THREAD

**Issue by e7a-0-e7a** [ConnorLinfoot/TitleAPI#23]
```

21:46:47] [Server thread/WARN]: [TitleAPI] Failed to handle reflection
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredClasses()" because the return value of "com.connorlinfoot.titleapi.ReflectionTitleAPI.getNMSClass(String)" is null
        at com.connorlinfoot.titleapi.ReflectionTitleAPI.sendTitle(ReflectionTitleAPI.java:50) ~[?:?]
        at com.connorlinfoot.titleapi.TitleAPI.sendTitle(TitleAPI.java:56) ~[?:?]
        at com.connorlinfoot.titleapi.TitleAPI.sendTitle(TitleAPI.java:39) ~[?:?]
        at de.B3auX.ml.events.Events.onJoin(Events.java:31) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:276) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3190-Spigot-d03d7f1-8ffa54b]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

```java

        @EventHandler
	public void onJoin(PlayerJoinEvent jevent) {

		Player player = jevent.getPlayer();

		if (Kiel.instance.getConfig().getBoolean("title-onJoin")) {
			TitleAPI.sendTitle(player, 
                                                    Kiel.instance.getConfig().getInt("title-fadeIn"), 
                                                    Kiel.instance.getConfig().getInt("title-stay"), 
                                                    Kiel.instance.getConfig().getInt("title-fadeOut"),
					            Kiel.color(Kiel.instance.getConfig().getString("title-message")), 
                                                    Kiel.color(Kiel.instance.getConfig().getString("title-subMessage")));
		}

	}

```

`at de.B3auX.ml.events.Events.onJoin(Events.java:31) ~[?:?]` is `TitleAPI.sendTitle( ...`

I don't see where the error is. Unfortunately, I have also found no other contact option than this one.

**Comment by ConnorLinfoot** [comment]
What server version and build is this?

**Comment by e7a-0-e7a** [comment]
The server is version 1.17.1 and is the latest build. (created yesterday via BuildTools)

**Comment by B3auX87** [comment]
Oh and if you mean the build of Title-API: TitleAPI v1.8
