### ISSUE TITLE
TitleAPI error

### ISSUE THREAD

**Issue by patrickwebsdev** [ConnorLinfoot/TitleAPI#25]
Hi! I'm trying to send Titles and subtitles with your API, but cannot this.
I am using:
Server: Spigot 1.8.8 R3
Maven:
- Spigot-api: 1.16.5-R0.1-SNAPSHOT
- Spigot: 1.16.5-R0.1-SNAPSHOT
- TitleAPI: 1.8.1
My code is:
`TitleAPI.sendTitle(player,20,80,20,"Title","Subtitle");` (as in your example)
But i get the error:
`org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin TestPlugin v3.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/connorlinfoot/titleapi/TitleAPI
	at com.Tecnico09.TestPlugin.Commands.Commands.<init>(Commands.java:166) ~[?:?]
	at com.Tecnico09.TestPlugin.Main.onCommand(Main.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.connorlinfoot.titleapi.TitleAPI
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.Tecnico09.TestPlugin.Commands.Commands.<init>(Commands.java:166) ~[?:?]
	at com.Tecnico09.TestPlugin.Main.onCommand(Main.java:25) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	... 16 more`

**Comment by ConnorLinfoot** [comment]
> java.lang.NoClassDefFoundError: com/connorlinfoot/titleapi/TitleAPI at 

You don't have the plugin installed, or there is another error somewhere in your console.

**Comment by patrickwebsdev** [comment]
> > java.lang.NoClassDefFoundError: com/connorlinfoot/titleapi/TitleAPI at
> 
> You don't have the plugin installed, or there is another error somewhere in your console.

Oh lol, it's true, sorry.
Yesterday I was doing it all day trying to work and I did not succeed due to different errors, today I saw that you uploaded this update and I wanted to try again (but I forgot to put TitleAPI back in my plugins).
Thank you very much for this API, it is already working correctly for me.
